# Generated by Django 2.2.9 on 2022-10-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('subject', models.CharField(max_length=100, verbose_name='Объект')),
                ('body', models.TextField(verbose_name='Тело')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Ответил')),
            ],
        ),
    ]
